name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Navigate to your project directory
            cd /home/ubuntu/brainly-backend
            
            # Pull the latest code
            git pull
            
            # Install dependencies
            npm install
            
            # Build the application
            npx tsc -b
            
            # Restart the application with PM2
            sudo pm2 restart brainly-be